#!/bin/sh

opdater_molly(){
  echo "Opdaterer Molly Wallet... " && echo
  cd ~/BUIDL/go/bin/molly_wallet && echo && git init && echo && echo "Sender pull-anmodning til Stardust Collectives github... " && echo &&  git pull && echo
}

opdater_hathor(){
  echo "Opdaterer Hathor Wallet... " && echo
  cd ~/BUIDL/hathor-wallet && echo && git init && echo && echo "Sender pull-anmodning til Hathor Labs github... " && echo && git pull && echo
} 

opdater_atom(){
sudo curl -o /usr/local/bin/atomicwallet.AppImage https://get.atomicwallet.io/download/atomicwallet.AppImage && chmod a+x /usr/local/bin/atomicwallet.AppImage && sudo cp /tmp/atomic_wallet_checksum.tmp ~/.config/atomic_wallet/atomic_wallet_checksum
echo "Rydder op..." && echo
rm /tmp/atomic_wallet_checksum.tmp | [[ "$?" == "0" ]]
}

tjek_version(){

### ATOMIC WALLET ###

# Mappen ikke fundet

[[ ! -d ~/.config/atomic_wallet/ ]] && echo "Opretter mappe til opdatering af Atomic Wallet" &&  mkdir ~/.config/atomic_wallet && echo "Oprettede mappen ~/.config/atomic_wallet"

 # Ingen checksum fundet i mappen
 
[[ ! -f ~/.config/atomic_wallet/atomic_wallet_checksum ]] && echo "Ingen checksum-fil fundet. Geninstallerer Atomic Wallet..." && echo && opdater_atom

# Hent og tjek Atomic Wallet checksum

echo "Henter Atomic Wallet checksum..." && echo
curl -o /tmp/atomic_wallet_checksum.tmp https://get.atomicwallet.io/download/sha256sum.txt && echo

ny_atom_checksum=$(cat </tmp/atomic_wallet_checksum.tmp | awk '/atomicwallet.AppImage/ {print $1}')
atom_checksum=$(cat <~/.config/atomic_wallet/atomic_wallet_checksum | awk '/atomicwallet.AppImage/ {print $1}')

# Opdatering fundet

[[ "$ny_atom_checksum" != "$atom_checksum" ]] && echo "Atomic Wallet bør opdateres. Starter opdatering..." && echo && opdater_atom

# Atomic Wallet er opdateret

[[ "$ny_atom_checksum" == "$atom_checksum" ]] && echo "Den nyeste version af Atomic Wallet findes allerede i systemet." && echo && echo "Rydder op..." && rm /tmp/atomic_wallet_checksum.tmp | [[ "$?" == "0" ]] && echo
}

opdater(){

# Opdater Atom

[[ "$1" == "atom" ]] && tjek_version

# Opdater hele systemet

[[ -z "$1" ]] && stat="system" && echo "Opdaterering af systemet startes ..." && yay -Syu $@ && echo
[[ "$1" == *"--"* ]] && stat="system" && echo "Opdaterering af systemet startes med argumentet \"$1 $2\" ..." &&  yay -Syu $@ && echo
 
[[ "$stat" == "system" ]] && tjek_version && opdater_molly && opdater_hathor
 
}

opdater $@
echo "Færdig!"
