#!/bin/sh

     start_x(){
       clear
       tput cup 0
       tput civis
       for i in {1..23000}; do
         [[ "$i" < "20000" ]] && echo -ne "\r\e[36m:)                          " &>/dev/tty
         [[ "$i" > "20001" ]] && echo -ne "\r\e[35m:|                          " &>/dev/tty
         [[ "$i" == "23000" ]] && break
       done &>/dev/null
       echo -e "\e[37m"
     }

     kill_x(){
       clear
       tput civis
       for i in {1..23000}; do
         [[ "$i" < "10000" ]] && echo -ne "\r\e[35mAfslutter x ..." &>/dev/tty
         [[ "$i" > "10001" ]] && echo -ne "\r" &>/dev/tty
         [[ "$i" == "23000" ]] && break
       done &>/dev/null
       killall xinit &>/dev/null
     tput cvvis
     }

modtaget_argument(){
  [[ "$1" == "start_x" ]] && start_x && startx &>/dev/null
  [[ "$1" == "kill_x" ]] && kill_x && clear && zsh
}

modtaget_argument $@
exit 1
