#!/bin/sh

gitorquit(){
echo
echo "Git overførsel? [j/n] "
while true; do
  read -rsn1 git
  case $git in
    "j" | "J" )
      git_commit
      ;;
    "n" | "N" )
      break
      ;;
  esac
done
}

git_commit(){
  echo
  [[ "$PWD" != ~/dots ]] && cd ~/dots
  git init ~/dots &>/dev/null && [[ "$?" == "0" ]] && echo "> Git init"
  git add . && [[ "$?" == "0" ]] && echo "> Git add"
  echo
  echo " [ANGIV ÆNDRINGER]"
  echo
  read -p "Titel: " titel
  read -p "Tekst: " txt
  echo
  git commit -m "$titel" -m "$txt" &>/dev/null && echo "> Git commit, med titlen \"$titel\""
  echo
  git push master && [[ "$?" == "0" ]] && echo && echo "> Dot skript slut."
  echo
  exit 0
}

kopi(){
echo
echo
echo " [SYSTEMMAPPENS KONFIGURATIONSFILER]"

[[ -d ~/dots/zsh-konfiguration ]] && rm -rf ~/dots/zsh
[[ ! -d ~/dots/zsh-konfiguration ]] && mkdir ~/dots/zsh-konfiguration && mkdir ~/dots/zsh-konfiguration/etc && mkdir ~/dots/zsh-konfiguration/etc/zsh
echo
echo "  [zsh-konfigurationer]"
echo
[[ -f /etc/zsh/zshenv ]] && sudo cp /etc/zsh/zshenv ~/dots/zsh-konfiguration/etc/zsh/
[[ -f /etc/zsh/zprofile ]] && sudo cp /etc/zsh/zprofile ~/dots/zsh-konfiguration/etc/zsh/
[[ -f /etc/zsh/zshrc ]] && sudo cp /etc/zsh/zshrc ~/dots/zsh-konfiguration/etc/zsh/
[[ -f /etc/zsh/zlogin ]] && sudo cp /etc/zsh/zlogin ~/dots/zsh-konfiguration/etc/zsh/
[[ -f /etc/zsh/zlogout ]] && sudo cp /etc/zsh/zlogout ~/dots/zsh-konfiguration/etc/zsh/
echo
echo " [HJEMMEMAPPENS KONFIGURATIONSFILER]"
echo
[[ -f ~/.zshenv ]] && sudo cp ~/.zshenv ~/dots/
[[ -f ~/.zshrc ]] && sudo cp ~/.zshrc ~/dots/
echo "  [bash/zsh konfigurationer]"
echo
[[ -f ~/.profile ]] && cp -rf ~/.profile ~/dots/ && [[ "$?" == "0" ]] && echo "-> .profile kopieret" || echo " X .profile ikke fundet"
echo
echo "  [bash konfigurationer]"
echo
[[ -f ~/.bashrc ]] && cp -rf ~/.bashrc ~/dots/ && [[ "$?" == "0" ]] && echo "-> .bashrc kopieret" || echo " X .bashrc ikke fundet"
[[ -f ~/.bash_profile ]] && cp -rf ~/.bash_profile ~/dots/ && [[ "$?" == "0" ]] && echo "-> .bash_profile kopieret" || echo " X .bash_profile ikke fundet"
#[[ -f ~/.alias ]] && cp -rf ~/.alias ~/dots/ && [[ "$?" == "0" ]] && echo "-> .alias kopieret" || echo " X .alias ikke fundet"
echo
echo '  [dwm konfigurationer]'
echo
[[ -d ~/.config/dwm/blocks ]] && cp -rf ~/.config/dwm/blocks ~/dots/dwm/.config/dwm/ && [[ "$?" == "0" ]] && echo "-> dwm-blokke kopieret" || echo " X dwm-blokke ikke fundet"
[[ -f ~/.config/dwm/status.sh ]] && cp -rf ~/.config/dwm/status.sh ~/dots/dwm/.config/dwm/ && [[ "$?" == "0" ]] && echo "-> dwm statusbar kopieret" || echo " X dwm-statusbar ikke fundet"
[[ -d ~/dots/dwm/dwm_source ]] && rm -rf ~/dots/dwm/dwm_source && [[ "$?" == "0" ]] && echo "-> slettede dwm-kildemappen" || echo " X dwm-kildemappen kan ikke slettes, hvis denne mangler, opretts den i næste trin"
[[ -d ~/dots/dwm/dwm_source ]] && [[ -d ~/dwm ]] && cp -rf ~/dwm ~/dots/dwm/dwm_source && [[ "$?" == "0" ]] && echo "-> dwm-kildemappen kopieret" || echo "-> dwm-kildemappen ikke fundet, opretter mappen..." && mkdir ~/dots/dwm/dwm_source && cp -rf ~/dwm ~/dots/dwm/dwm_source && [[ "$?" == "0" ]] && echo "-> dwm-kildemappen kopieret" || echo " X Noget gik galt"

echo
echo "  [autostart]"
echo
[[ -f ~/.local/bin/autostart.sh ]] && cp -rf ~/.local/bin/autostart.sh ~/dots/dwm/.local/bin/ && [[ "$?" == "0" ]] && echo "-> autostart.sh kopieret" || echo " X autostart.sh kopieret"
echo
echo "  [vim konfigurationer]"
echo
[[ -f ~/.vimrc ]] && cp -rf ~/.vimrc ~/dots/ && [[ "$?" == "0" ]] && echo "-> .vimrc kopieret" || echo " X .vimrc ikke fundet"
echo
echo "  [xorg konfiguration]"
echo
[[ -f ~/.xinitrc ]] && cp -rf ~/.xinitrc ~/dots/dwm/ && [[ "$?" == "0" ]] && echo "-> .xinitrc kopieret" || echo " X .xinitrc ikke fundet"
[[ -f ~/.Xresources ]] && cp -rf ~/.Xresources ~/dots/ && [[ "$?" == "0" ]] && echo "-> .Xresources kopieret" || echo " X .Xresources ikke fundet"
echo
echo
echo " [HJEMMEBRYG]"
echo
echo "  [netto-skript]"
echo
[[ -f /usr/bin/netto ]] && cp -rf /usr/bin/netto ~/dots/hjemmebryg/netto/ && [[ "$?" == "0" ]] && echo "-> netto-skript kopieret" || echo " X netto-skript ikke fundet"
echo
echo "  [bat-skript]"
echo
[[ -f /usr/bin/bat ]] && cp -rf /usr/bin/bat ~/dots/hjemmebryg/div/ && [[ "$?" == "0" ]] && echo "-> bat-skript kopieret" || echo " X bat-skript ikke fundet" 
echo
echo "  [rens-skript]"
echo
[[ -f /usr/bin/rens ]] && cp -rf /usr/bin/rens ~/dots/hjemmebryg/div/ && [[ "$?" == "0" ]] && echo "-> rens-skript kopieret" || echo " X rens-skript ikke fundet"
gitorquit
exit 0
}

echo
echo "  michacode@github"
echo
echo "@@@@@@@@@@@@@@@@@@@@"
echo "--------------------"
echo " DDD   OO DDDDD ZZ  "
echo " D  D O  O  D  Z  Z "
echo " D  D O  O  D   Zz  "
echo " D  D D  D  D     Z "
echo " DDD   OO   D  ZzzZ "
echo "--------------------"
echo "@@@@@@@@@@@@@@@@@@@@"

[[ ! -d ~/dots ]] && echo "[INGEN DOT-MAPPE FUNDET, AFSLUTTER SKRIPT...]" && exit 0 || [[ -d ~/dots ]] && kopi || echo "[NOGET GIK GALT, AFSLUTTER]" && exit 0
exit 0
