#!/bin/sh

gitorquit(){
echo
echo "Git overførsel? [j/n] "
while true; do
  read -rsn1 git
  case $git in
    "j" | "J" )
      git_commit
      ;;
    "n" | "N" )
      break
      ;;
  esac
done
}

git_commit(){
  echo
  git init ~/dots &>/dev/null && [[ "$?" == "0" ]] && echo "> Git startet i dots-mappen"
  git add . && [[ "$?" == "0" ]] && echo "> Filerne blev tilføjet git master"
  echo
  echo "[ANGIV ÆNDRINGER]"
  read -p "Titel: " titel
  read -p "Tekst: " txt
  echo
  git commit -m "$titel" -m "$txt" &>/dev/null && echo "> Git commit, med titlen \"$titel\" lykkedes"
  echo
  git push master &>/dev/null && [[ "$?" == "0" ]] && echo "> Git overførsel lykkedes"
  echo
  exit 0
}

kopi(){
echo
echo
echo " [HJEMMEMAPPENS KONFIGURATIONSFILER]"
echo
echo " [bash konfigurationer]"
echo
[[ -f ~/.bashrc ]] && cp -rf ~/.bashrc ~/dots/ && [[ "$?" == "0" ]] && echo "-> .bashrc kopieret" || echo " X .bashrc ikke fundet"
[[ -f ~/.bash_profile ]] && cp -rf ~/.bash_profile ~/dots/ && [[ "$?" == "0" ]] && echo "-> .bash_profile kopieret" || echo " X .bash_profile ikke fundet"
echo
echo ' [dwm konfigurationer]'
echo
[[ -d ~/.config/dwm/blocks ]] && cp -rf ~/.config/dwm/blocks ~/dots/dwm/.config/dwm/ && [[ "$?" == "0" ]] && echo "-> dwm-blokke kopieret" || echo " X dwm-blokke ikke fundet"
[[ -f ~/.config/dwm/status.sh ]] && cp -rf ~/.config/dwm/status.sh ~/dots/dwm/.config/dwm/ && [[ "$?" == "0" ]] && echo "-> dwm statusbar kopieret" || echo " X dwm-statusbar ikke fundet"
[[ -d ~/dots/dwm/dwm_source ]] && rm -rf ~/dots/dwm/dwm_source && [[ "$?" == "0" ]] && echo "-> slettede mappen dwm/dwm_source" || echo " X mappen dwm/dwm_source ikke fundet eller kan ikke slettes"
[[ -d ~/dots/dwm/dwm_source ]] && [[ -d ~/dwm ]] && cp -rf ~/dwm ~/dots/dwm/dwm_source && [[ "$?" == "0" ]] && echo "-> dwm-kildemappen kopieret" || echo " X dwm-kildemappen ikke fundet eller kan ikke kopieres"

echo
echo " [autostart]"
echo
[[ -f ~/.local/bin/autostart.sh ]] && cp -rf ~/.local/bin/autostart.sh ~/dots/dwm/.local/bin/ && [[ "$?" == "0" ]] && echo "-> autostart.sh kopieret" || echo " X autostart.sh kopieret"
echo
echo " [vim konfigurationer]"
echo
[[ -f ~/.vimrc ]] && cp -rf ~/.vimrc ~/dots/ && [[ "$?" == "0" ]] && echo "-> .vimrc kopieret" || echo " X .vimrc ikke fundet"
echo
echo " [xorg konfiguration]"
echo
[[ -f ~/.xinitrc ]] && cp -rf ~/.xinitrc ~/dots/dwm/ && [[ "$?" == "0" ]] && echo "-> .xinitrc kopieret" || echo " X .xinitrc ikke fundet"
[[ -f ~/.Xresources ]] && cp -rf ~/.Xresources ~/dots/ && [[ "$?" == "0" ]] && echo "-> .Xresources kopieret" || echo " X .Xresources ikke fundet"
echo
echo
echo " [HJEMMEBRYG]"
echo
echo " [netto-skript]"
echo
[[ -f /usr/bin/netto ]] && cp -rf /usr/bin/netto ~/dots/hjemmebryg/netto/ && [[ "$?" == "0" ]] && echo "-> netto-skript kopieret" || echo " X netto-skript ikke fundet"
echo
echo " [bat-skript]"
echo
[[ -f /usr/bin/bat ]] && cp -rf /usr/bin/bat ~/dots/hjemmebryg/div/ && [[ "$?" == "0" ]] && echo "-> bat-skript kopieret" || echo " X bat-skript ikke fundet" 
gitorquit
exit 0
}

echo
echo "  michacode@github"
echo
echo "@@@@@@@@@@@@@@@@@@@@"
echo "--------------------"
echo " DDD   OO DDDDD ZZ  "
echo " D  D O  O  D  Z  Z "
echo " D  D O  O  D   Zz  "
echo " D  D D  D  D     Z "
echo " DDD   OO   D  ZzzZ "
echo "--------------------"
echo "@@@@@@@@@@@@@@@@@@@@"
echo
[[ ! -d ~/dots ]] && echo "[INGEN DOT-MAPPE FUNDET, AFSLUTTER SKRIPT...]" && exit 0 || [[ -d ~/dots ]] && kopi || echo "[NOGET GIK GALT, AFSLUTTER]" && exit 0
exit 0
