#!/bin/sh

gitorquit(){
echo
echo "Git push? [j/n] "
while true; do
  read -rsn1 git
  case $git in
    "j" | "J" )
      git_commit
      ;;
    "n" | "N" )
      break
      ;;
  esac
done
}

git_commit(){
  echo
  git init ~/dots &>/dev/null && [[ "$?" == "0" ]] && echo "> Git init lykkedes"
  git add . && [[ "$?" == "0" ]] && echo "> Git tilføj lykkedes"
  echo
  echo "Angiv ændringer."
  read -p "Titel: " titel
  read -p "Tekst: " txt
  git commit -m "$titel" -m "$txt" &>/dev/null && echo "> Git commit, med titlen \"$titel\" lykkedes"
  git push master &>/dev/null && [[ "$?" == "0" ]] && echo "> Git push lykkedes"
  
  exit 0

}

echo
echo "  michacode@github"
echo
echo "@@@@@@@@@@@@@@@@@@@@"
echo "--------------------"
echo " DDD   OO DDDDD ZZ  "
echo " D  D O  O  D  Z  Z "
echo " D  D O  O  D   Zz  "
echo " D  D D  D  D     Z "
echo " DDD   OO   D  ZzzZ "
echo "--------------------"
echo "@@@@@@@@@@@@@@@@@@@@"
echo
echo
echo "Kopierer: "
echo
echo " * bash konfigurationer"
echo
[[ -f ~/.bashrc ]] && cp -rf ~/.bashrc ~/dots/ && [[ "$?" == "0" ]] && echo "-> .bashrc kopieret" || echo " X .bashrc ikke fundet"
[[ -f ~/.bash_profile ]] && cp -rf ~/.bash_profile ~/dots/ && [[ "$?" == "0" ]] && echo "-> .bash_profile kopieret" || echo " X .bash_profile ikke fundet"
echo
echo ' * dwm konfigurationer'
echo
[[ -d ~/.config/dwm/blocks ]] && cp -rf ~/.config/dwm/blocks ~/dots/dwm/.config/dwm/ && [[ "$?" == "0" ]] && echo "-> dwm-blokke kopieret" || echo " X dwm-blokke ikke fundet"
[[ -f ~/.config/dwm/status.sh ]] && cp -rf ~/.config/dwm/status.sh ~/dots/dwm/.config/dwm/ && [[ "$?" == "0" ]] && echo "-> dwm statusbar kopieret" || echo " X dwm-statusbar ikke fundet"
rm -r ~/dots/dwm/dwm_source
cp -rf ~/dwm ~/dots/dwm/dwm_source
echo
echo " * autostart.sh"
cp -rf ~/.local/bin/autostart.sh ~/dots/dwm/.local/bin/
echo
echo " * vim konfigurationer"
cp -rf ~/.vimrc ~/dots/
echo
echo " * x konfiguration"
cp -rf ~/.xinitrc ~/dots/dwm/
cp -rf ~/.Xresources ~/dots/
echo
echo "  hjemmebryg:"
echo
echo " * netto skript"
echo
cp -rf /usr/bin/netto ~/dots/hjemmebryg/netto/
echo " * bat skript"
cp -rf /usr/bin/bat ~/dots/hjemmebryg/div/
gitorquit
exit 0
