#!/usr/bin/env bash

echo "michacode@github:"
echo
echo "@@@@@@@@@@@@@@@@@@@@"
echo "--------------------"
echo "DDD   OO  DDDDD  ZZ "
echo "D  D O  O   D   Z  Z"
echo "D  D O  O   D    Zz "
echo "D  D D  D   D      Z"
echo "DDD   OO    D   ZzzZ"
echo "--------------------"
echo "@@@@@@@@@@@@@@@@@@@@"
echo
echo
echo "Kopierer: "
echo
echo "* bash konfigurationer"
cp -rf ~/.bashrc ~/dots/
cp -rf ~/.bash_profile ~/dots/
echo
echo '* dwm konfigurationer'
cp -rf ~/.config/dwm/blocks ~/dots/dwm/.config/dwm/
cp -rf ~/.config/dwm/status.sh ~/dots/dwm/.config/dwm/
rm -r ~/dots/dwm/dwm_source
cp -rf ~/dwm ~/dots/dwm/dwm_source
echo
echo "* autostart.sh"
cp -rf ~/.local/bin/autostart.sh ~/dots/dwm/.local/bin/
echo
echo "* vim konfigurationer"
cp -rf ~/.vimrc ~/dots/
echo
echo "* x konfiguration"
cp -rf ~/.xinitrc ~/dots/dwm/
cp -rf ~/.Xresources ~/dots/
echo
echo "  hjemmebryg:"
echo
echo "* netto skript"
echo
cp -rf /usr/bin/netto ~/dots/hjemmebryg/netto/
echo "* bat skript"
cp -rf /usr/bin/bat ~/dots/hjemmebryg/div/
exit 0
