#!/usr/bin/env bash

echo "Kopierer: "
echo
echo "bash konf."
cp -rf ~/.bashrc ~/dots/
echo 'dwm konf.'
cp -rf ~/.config/dwm/blocks ~/dots/dwm/.config/dwm/
cp -rf ~/.config/dwm/status.sh ~/dots/dwm/.config/dwm/
cp -rf ~/dwm ~/dots/dwm/dwm_source
echo "autostart.sh"
cp -rf ~/.local/bin/autostart.sh ~/dots/dwm/.local/bin/
echo "vim konf."
cp -rf ~/.vimrc ~/dots/
echo "x konf."
cp -rf ~/.xinitrc ~/dots/dwm/
cp -rf ~/.Xresources ~/dots/
exit 0
